# Generated by Django 3.1.1 on 2020-09-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20200903_1429'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
