# Generated by Django 3.1.1 on 2020-09-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_management', '0003_auto_20200903_1614'),
        ('user_management', '0003_auto_20200903_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
