# Generated by Django 3.1.1 on 2020-09-03 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_management', '0002_auto_20200903_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.user'),
            preserve_default=False,
        ),
    ]
