# Generated by Django 3.1.1 on 2020-09-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_management', '0003_auto_20200903_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
